name: generate artifacts
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  documentation:
    name: generate ex_doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 22.1.7
          elixir-version: 1.9.4
      - name: genereate doc
        run: |
          mix deps.get
          mix docs
      - name: deploy to now
        run: now --token ${{ secrets.NOW_TOKEN }} -n phx_artifact doc/

  credo:
    name: run credo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 22.1.7
          elixir-version: 1.9.4
      - name: setup reviewdog
        run: |
          mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin
          echo ::add-path::$HOME/bin
      - uses: actions/checkout@v1
      - run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: run credo and report
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mix credo suggest --strict --format=flycheck \
            | reviewdog -efm="%f:%l:%c: %t: %m" -efm="%f:%l: %t: %m" -name="credo" -reporter="github-pr-check" -level="error"

  coverage:
    name: generate test coverage report
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 22.1.7
          elixir-version: 1.9.4
      - name: report
        run: |
          mix deps.get
          mix coveralls.github
