name: generate artifacts
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  documentation:
    name: generate ex_doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 22.1.7
          elixir-version: 1.9.4
      - name: genereate doc
        run: |
          mix deps.get
          mix docs
      - name: deploy to now
        run: now --token ${{ secrets.NOW_TOKEN }} -n phx_artifact doc/

  credo:
    name: run credo
    runs-on: ubuntu-latest
    container:
      image: elixir:1.9.1-slim
    steps:
      - uses: actions/checkout@v1
      - run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: run credo and report
        uses: red-shirts/reviewdog-action-credo@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check

  coverage:
    name: generate test coverage report
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 22.1.7
          elixir-version: 1.9.4
      - name: report
        run: |
          mix deps.get
          mix coveralls.github
